import { TechProvider } from '@/context/TechContext'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TechProvider>
        <body>{children}</body>
      </TechProvider>
    </html>
  )
}
