import { TechProvider } from '@/context/TechContext'
import './globals.css'
import Navbar from '@/components/Navbar'
import { Toaster } from './toaster'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TechProvider>
        <body>
          <Navbar />
          {children}
          <Toaster />
        </body>
      </TechProvider>
    </html>
  )
}
